import { OpponentConfiguration } from '../types/types';

export const DEFAULT_ENERGY_MOD = 1;
export const T5_MAX_ENERGY_MOD = 2;
export const T6_MAX_ENERGY_MOD = 15;

export const GENERAL_CONFIGS: OpponentConfiguration[] = [
  {
    opponentCpm: 0.15,
    opponentHp: 1700,
    opponentAtkMod: 1,
    opponentDefMod: 1,
    opponentName: 'T1 Dynamax',
    opponentMaxEnergyMod: DEFAULT_ENERGY_MOD,
  },
  {
    opponentCpm: 0.38,
    opponentHp: 5000,
    opponentAtkMod: 1,
    opponentDefMod: 1,
    opponentName: 'T2 Dynamax',
    opponentMaxEnergyMod: DEFAULT_ENERGY_MOD,
  },
  {
    opponentCpm: 0.5,
    opponentHp: 10000,
    opponentAtkMod: 1,
    opponentDefMod: 1,
    opponentName: 'T3 Dynamax',
    opponentMaxEnergyMod: DEFAULT_ENERGY_MOD,
  },
  {
    opponentCpm: 0.6,
    opponentHp: 20000,
    opponentAtkMod: 1,
    opponentDefMod: 1,
    opponentName: 'T4 Dynamax',
    opponentMaxEnergyMod: DEFAULT_ENERGY_MOD,
  },
  {
    opponentCpm: 0.75,
    opponentHp: 22000,
    opponentAtkMod: 2,
    opponentDefMod: 1,
    opponentName: 'T5 Dynamax (Averaged)',
    opponentMaxEnergyMod: T5_MAX_ENERGY_MOD,
  },
  {
    opponentCpm: 0.9,
    opponentHp: 90000,
    opponentAtkMod: 0.9,
    opponentDefMod: 1,
    opponentName: 'T6 Gigantamax (Averaged)',
    opponentMaxEnergyMod: T6_MAX_ENERGY_MOD,
  },
];

export const SPECIFIC_CONFIGS: OpponentConfiguration[] = [
  { opponentName: 'Articuno', opponentCpm: 0.7, opponentHp: 17500, opponentAtkMod: 2.0, opponentDefMod: 1, opponentMaxEnergyMod: T5_MAX_ENERGY_MOD },
  { opponentName: 'Zapdos', opponentCpm: 0.7, opponentHp: 13000, opponentAtkMod: 2.0, opponentDefMod: 1, opponentMaxEnergyMod: T5_MAX_ENERGY_MOD },
  { opponentName: 'Moltres', opponentCpm: 0.7, opponentHp: 20000, opponentAtkMod: 2.0, opponentDefMod: 1, opponentMaxEnergyMod: T5_MAX_ENERGY_MOD },
  { opponentName: 'Raikou', opponentCpm: 0.8, opponentHp: 25000, opponentAtkMod: 2.0, opponentDefMod: 1, opponentMaxEnergyMod: T5_MAX_ENERGY_MOD },
  { opponentName: 'Entei', opponentCpm: 0.75, opponentHp: 27000, opponentAtkMod: 2.0, opponentDefMod: 1, opponentMaxEnergyMod: T5_MAX_ENERGY_MOD },
  { opponentName: 'Suicune', opponentCpm: 0.9, opponentHp: 22000, opponentAtkMod: 2.0, opponentDefMod: 1, opponentMaxEnergyMod: T5_MAX_ENERGY_MOD },
  { opponentName: 'Latias', opponentCpm: 0.7, opponentHp: 25000, opponentAtkMod: 2.0, opponentDefMod: 1, opponentMaxEnergyMod: T5_MAX_ENERGY_MOD },
  { opponentName: 'Latios', opponentCpm: 0.75, opponentHp: 23000, opponentAtkMod: 2.0, opponentDefMod: 1, opponentMaxEnergyMod: T5_MAX_ENERGY_MOD },
  { opponentName: 'Venusaur', opponentCpm: 0.85, opponentHp: 80000, opponentAtkMod: 0.9, opponentDefMod: 1, opponentMaxEnergyMod: T6_MAX_ENERGY_MOD },
  {
    opponentName: 'Charizard',
    opponentCpm: 0.85,
    opponentHp: 80000,
    opponentAtkMod: 0.9,
    opponentDefMod: 1,
    opponentMaxEnergyMod: T6_MAX_ENERGY_MOD,
  },
  {
    opponentName: 'Blastoise',
    opponentCpm: 0.85,
    opponentHp: 80000,
    opponentAtkMod: 0.9,
    opponentDefMod: 1,
    opponentMaxEnergyMod: T6_MAX_ENERGY_MOD,
  },
  {
    opponentName: 'Butterfree',
    opponentCpm: 0.85,
    opponentHp: 100000,
    opponentAtkMod: 0.9,
    opponentDefMod: 1,
    opponentMaxEnergyMod: T6_MAX_ENERGY_MOD,
  },
  { opponentName: 'Machamp', opponentCpm: 0.8, opponentHp: 100000, opponentAtkMod: 0.9, opponentDefMod: 1, opponentMaxEnergyMod: T6_MAX_ENERGY_MOD },
  { opponentName: 'Gengar', opponentCpm: 0.85, opponentHp: 80000, opponentAtkMod: 0.9, opponentDefMod: 1, opponentMaxEnergyMod: T6_MAX_ENERGY_MOD },
  { opponentName: 'Kingler', opponentCpm: 0.85, opponentHp: 100000, opponentAtkMod: 0.9, opponentDefMod: 1, opponentMaxEnergyMod: T6_MAX_ENERGY_MOD },
  { opponentName: 'Lapras', opponentCpm: 0.45, opponentHp: 100000, opponentAtkMod: 0.75, opponentDefMod: 1, opponentMaxEnergyMod: T6_MAX_ENERGY_MOD },
  { opponentName: 'Snorlax', opponentCpm: 0.85, opponentHp: 100000, opponentAtkMod: 0.9, opponentDefMod: 1, opponentMaxEnergyMod: T6_MAX_ENERGY_MOD },
  {
    opponentName: 'Rillaboom',
    opponentCpm: 1.0,
    opponentHp: 120000,
    opponentAtkMod: 0.9,
    opponentDefMod: 1,
    opponentMaxEnergyMod: T6_MAX_ENERGY_MOD,
  },
  { opponentName: 'Cinderace', opponentCpm: 0.8, opponentHp: 80000, opponentAtkMod: 0.9, opponentDefMod: 1, opponentMaxEnergyMod: T6_MAX_ENERGY_MOD },
  { opponentName: 'Inteleon', opponentCpm: 0.9, opponentHp: 100000, opponentAtkMod: 0.9, opponentDefMod: 1, opponentMaxEnergyMod: T6_MAX_ENERGY_MOD },
  {
    opponentName: 'Toxtricity',
    opponentCpm: 0.9,
    opponentHp: 160000,
    opponentAtkMod: 1.15,
    opponentDefMod: 1,
    opponentMaxEnergyMod: T6_MAX_ENERGY_MOD,
  },
  {
    opponentName: 'Eternatus (Eternamax)',
    opponentCpm: 0.75,
    opponentHp: 60000,
    opponentAtkMod: 0.9,
    opponentDefMod: 1,
    opponentMaxEnergyMod: T6_MAX_ENERGY_MOD,
  },
  { opponentName: 'Garbodor', opponentCpm: 1.4, opponentHp: 100000, opponentAtkMod: 0.9, opponentDefMod: 1, opponentMaxEnergyMod: T6_MAX_ENERGY_MOD },
  {
    opponentName: 'Grimmsnarl',
    opponentCpm: 1.2,
    opponentHp: 70000,
    opponentAtkMod: 0.9,
    opponentDefMod: 1,
    opponentMaxEnergyMod: T6_MAX_ENERGY_MOD,
  },
  { opponentName: 'Ho-Oh', opponentCpm: 0.7, opponentHp: 27000, opponentAtkMod: 2, opponentDefMod: 1, opponentMaxEnergyMod: T5_MAX_ENERGY_MOD },
  { opponentName: 'Meowth', opponentCpm: 3.0, opponentHp: 80000, opponentAtkMod: 1, opponentDefMod: 1, opponentMaxEnergyMod: T6_MAX_ENERGY_MOD },
  { opponentName: 'Regice', opponentCpm: 0.8, opponentHp: 20000, opponentAtkMod: 2, opponentDefMod: 1, opponentMaxEnergyMod: T5_MAX_ENERGY_MOD },
  { opponentName: 'Pikachu', opponentCpm: 1.7, opponentHp: 80000, opponentAtkMod: 1, opponentDefMod: 1, opponentMaxEnergyMod: T6_MAX_ENERGY_MOD },
  { opponentName: 'Regirock', opponentCpm: 0.8, opponentHp: 20000, opponentAtkMod: 2, opponentDefMod: 1, opponentMaxEnergyMod: T5_MAX_ENERGY_MOD },
];
