import { OpponentConfiguration } from '../types/types';

export const GENERAL_CONFIGS: OpponentConfiguration[] = [
  {
    opponentCpm: 0.15,
    opponentHp: 1700,
    opponentAtkMod: 1,
    opponentDefMod: 1,
    opponentName: 'T1 Dynamax',
  },
  {
    opponentCpm: 0.38,
    opponentHp: 5000,
    opponentAtkMod: 1,
    opponentDefMod: 1,
    opponentName: 'T2 Dynamax',
  },
  {
    opponentCpm: 0.5,
    opponentHp: 10000,
    opponentAtkMod: 1,
    opponentDefMod: 1,
    opponentName: 'T3 Dynamax',
  },
  {
    opponentCpm: 0.6,
    opponentHp: 20000,
    opponentAtkMod: 1,
    opponentDefMod: 1,
    opponentName: 'T4 Dynamax',
  },
  {
    opponentCpm: 0.75,
    opponentHp: 22000,
    opponentAtkMod: 2,
    opponentDefMod: 1,
    opponentName: 'T5 Dynamax (Averaged)',
  },
  {
    opponentCpm: 0.9,
    opponentHp: 90000,
    opponentAtkMod: 0.9,
    opponentDefMod: 1,
    opponentName: 'T6 Gigantamax (Averaged)',
  },
];

export const SPECIFIC_CONFIGS: OpponentConfiguration[] = [
  { opponentName: 'Articuno', opponentCpm: 0.7, opponentHp: 17500, opponentAtkMod: 2.0, opponentDefMod: 1 },
  { opponentName: 'Zapdos', opponentCpm: 0.7, opponentHp: 13000, opponentAtkMod: 2.0, opponentDefMod: 1 },
  { opponentName: 'Moltres', opponentCpm: 0.7, opponentHp: 20000, opponentAtkMod: 2.0, opponentDefMod: 1 },
  { opponentName: 'Raikou', opponentCpm: 0.8, opponentHp: 25000, opponentAtkMod: 2.0, opponentDefMod: 1 },
  { opponentName: 'Entei', opponentCpm: 0.75, opponentHp: 27000, opponentAtkMod: 2.0, opponentDefMod: 1 },
  { opponentName: 'Suicune', opponentCpm: 0.9, opponentHp: 22000, opponentAtkMod: 2.0, opponentDefMod: 1 },
  { opponentName: 'Latias', opponentCpm: 0.7, opponentHp: 25000, opponentAtkMod: 2.0, opponentDefMod: 1 },
  { opponentName: 'Latios', opponentCpm: 0.75, opponentHp: 23000, opponentAtkMod: 2.0, opponentDefMod: 1 },
  { opponentName: 'Venusaur', opponentCpm: 0.85, opponentHp: 80000, opponentAtkMod: 0.9, opponentDefMod: 1 },
  { opponentName: 'Charizard', opponentCpm: 0.85, opponentHp: 80000, opponentAtkMod: 0.9, opponentDefMod: 1 },
  { opponentName: 'Blastoise', opponentCpm: 0.85, opponentHp: 80000, opponentAtkMod: 0.9, opponentDefMod: 1 },
  { opponentName: 'Butterfree', opponentCpm: 0.85, opponentHp: 100000, opponentAtkMod: 0.9, opponentDefMod: 1 },
  { opponentName: 'Machamp', opponentCpm: 0.8, opponentHp: 100000, opponentAtkMod: 0.9, opponentDefMod: 1 },
  { opponentName: 'Gengar', opponentCpm: 0.85, opponentHp: 80000, opponentAtkMod: 0.9, opponentDefMod: 1 },
  { opponentName: 'Kingler', opponentCpm: 0.85, opponentHp: 100000, opponentAtkMod: 0.9, opponentDefMod: 1 },
  { opponentName: 'Lapras', opponentCpm: 0.45, opponentHp: 100000, opponentAtkMod: 0.75, opponentDefMod: 1 },
  { opponentName: 'Snorlax', opponentCpm: 0.85, opponentHp: 100000, opponentAtkMod: 0.9, opponentDefMod: 1 },
  { opponentName: 'Rillaboom', opponentCpm: 1.0, opponentHp: 120000, opponentAtkMod: 0.9, opponentDefMod: 1 },
  { opponentName: 'Cinderace', opponentCpm: 0.8, opponentHp: 80000, opponentAtkMod: 0.9, opponentDefMod: 1 },
  { opponentName: 'Inteleon', opponentCpm: 0.9, opponentHp: 100000, opponentAtkMod: 0.9, opponentDefMod: 1 },
  { opponentName: 'Toxtricity', opponentCpm: 0.9, opponentHp: 160000, opponentAtkMod: 1.15, opponentDefMod: 1 },
  { opponentName: 'Eternatus (Eternamax)', opponentCpm: 0.75, opponentHp: 60000, opponentAtkMod: 0.9, opponentDefMod: 1 },
  { opponentName: 'Garbodor', opponentCpm: 1.4, opponentHp: 100000, opponentAtkMod: 0.9, opponentDefMod: 1 },
  { opponentName: 'Grimmsnarl', opponentCpm: 1.2, opponentHp: 70000, opponentAtkMod: 0.9, opponentDefMod: 1 },
  { opponentName: 'Ho-Oh', opponentCpm: 0.7, opponentHp: 27000, opponentAtkMod: 2, opponentDefMod: 1 },
  { opponentName: 'Meowth', opponentCpm: 3.4, opponentHp: 80000, opponentAtkMod: 1, opponentDefMod: 1 },
];
