import { OpponentConfiguration } from '../types/types';

export const CONFIGURATIONS: OpponentConfiguration[] = [
  {
    opponentName: 'Venusaur',
    opponentCpm: 0.85,
    opponentAtkMod: 1,
    opponentDefMod: 1,
    opponentHp: 90000,
  },
  {
    opponentName: 'Charizard',
    opponentCpm: 0.85,
    opponentAtkMod: 1,
    opponentDefMod: 1,
    opponentHp: 90000,
  },
  {
    opponentName: 'Blastoise',
    opponentCpm: 0.85,
    opponentAtkMod: 1,
    opponentDefMod: 1,
    opponentHp: 90000,
  },
  {
    opponentName: 'Gengar',
    opponentCpm: 0.765,
    opponentAtkMod: 1,
    opponentDefMod: 1,
    opponentHp: 90000,
  },
  {
    opponentName: 'Toxtricity',
    opponentCpm: 0.765,
    opponentAtkMod: 1.3333,
    opponentDefMod: 1,
    opponentHp: 135000,
  },
  {
    opponentName: 'Lapras',
    opponentCpm: 0.765,
    opponentAtkMod: 1,
    opponentDefMod: 1,
    opponentHp: 90000,
  },
  {
    opponentName: 'Kingler',
    opponentCpm: 0.765,
    opponentAtkMod: 1,
    opponentDefMod: 1,
    opponentHp: 115000,
  },
  {
    opponentName: 'Articuno',
    opponentCpm: 0.7,
    opponentAtkMod: 2,
    opponentDefMod: 1,
    opponentHp: 17500,
  },
  {
    opponentName: 'Zapdos',
    opponentCpm: 0.7,
    opponentAtkMod: 2,
    opponentDefMod: 1,
    opponentHp: 13000,
  },
  {
    opponentName: 'Moltres',
    opponentCpm: 0.7,
    opponentAtkMod: 2,
    opponentDefMod: 1,
    opponentHp: 17500,
  },
  {
    opponentName: 'Snorlax',
    opponentCpm: 0.765,
    opponentAtkMod: 1,
    opponentDefMod: 1,
    opponentHp: 115000,
  },
  {
    opponentName: 'Raikou',
    opponentCpm: 0.8,
    opponentAtkMod: 2,
    opponentDefMod: 1,
    opponentHp: 23000,
  },
  {
    opponentName: 'Entei',
    opponentCpm: 0.8,
    opponentAtkMod: 2,
    opponentDefMod: 1,
    opponentHp: 23000,
  },
  {
    opponentName: 'Suicune',
    opponentCpm: 0.8,
    opponentAtkMod: 2,
    opponentDefMod: 1,
    opponentHp: 22000,
  },
  {
    opponentName: 'Machamp',
    opponentCpm: 0.72,
    opponentAtkMod: 1,
    opponentDefMod: 1,
    opponentHp: 115000,
  },
  {
    opponentName: 'Rillaboom',
    opponentCpm: 0.9,
    opponentAtkMod: 1,
    opponentDefMod: 1,
    opponentHp: 135000,
  },
  {
    opponentName: 'Cinderace',
    opponentCpm: 0.72,
    opponentAtkMod: 1,
    opponentDefMod: 1,
    opponentHp: 80000,
  },
  {
    opponentName: 'Inteleon',
    opponentCpm: 0.81,
    opponentAtkMod: 1,
    opponentDefMod: 1,
    opponentHp: 100000,
  },
  {
    opponentName: 'Butterfree',
    opponentCpm: 0.765,
    opponentAtkMod: 1,
    opponentDefMod: 1,
    opponentHp: 100000,
  },
  {
    opponentName: 'Latios',
    opponentCpm: 0.75,
    opponentAtkMod: 2,
    opponentDefMod: 1,
    opponentHp: 23000,
  },
  {
    opponentName: 'Latias',
    opponentCpm: 0.7,
    opponentAtkMod: 2,
    opponentDefMod: 1,
    opponentHp: 25000,
  },
];
